nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200'] # Adjust this to your frontend URL
        allow_headers: ['Content-Type']
        allow_methods: ['POST', 'GET', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': # Apply the CORS settings to all API routes
            allow_origin: ['http://localhost:4200'] # Adjust this to your frontend URL
            allow_headers: ['Content-Type']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600
